Fix for empty CI environment
Running packpack makefiles during its checks found
that rpmbuild tool fails with undefined CI environment:
rpmbuild \
	--define '_topdir /tarantool/build' \
	--define '_sourcedir /tarantool/build' \
	--define '_specdir /tarantool/build' \
	--define '_srcrpmdir /tarantool/build' \
	--define '_ci ' \
	--define '_builddir /tarantool/build/usr/src/debug' \
	-bs /tarantool/build/tarantool.spec
error: Macro %_ci has empty body

rpmbuild tool fails due to '_ci' definition in options should
be used with some value either %{nil} predefined macro.

Follow up #4599